#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
defaults: &defaults      #引用默认值
  docker:
    - image: circleci/node:8        #node8

version: 2              #circleci的版本
jobs:                   #要做的步骤
  prepare:              #第一步，为node依赖们做缓存快照，加速缓存，省时间。
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:                                     #以package.json的MD5做对比
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout          #迁出代码
      - attach_workspace:      #把上面的node_modules拿过来
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - README.md
            - package.json
            - LICENSE
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:       #把缓存的代码拿过来
          at: .
      - run: yarn ci            #添加ci script
      - store_test_results:       #测试结果输出
          path: test-results

  publish:
    <<: *defaults
    steps:
      - attach_workspace:      #把上面的codes拿过来
          at: .
      - run: yarn publish

workflows:          #流程
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
          requires:    #各个流程间的依赖，决定了流程执行顺序
            - test
      - test:
          requires:
            - prepare
      - publish:
          requires:
            - build